<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceEF.Crud.Infrastructure.Context\InvoiceEF.Crud.Infrastructure.Context.csproj" />
    <ProjectReference Include="..\InvoiceEF.Crud.Infrastructure.Mappers\InvoiceEF.Crud.Infrastructure.Mappers.csproj" />
  </ItemGroup>

</Project>
